pinkary-project/pinkary.com

resources/views/layouts/navigation.blade.php
Thanks for open-sourcing Pinkary!
This PR updates the source code URL in the navigation bar to correctly point to the source code.
=> chore: update URL for source code

routes/console.php
Small change: 
replace `1` with `Carbon::MONDAY` in `console.php`
My first contribution to open source, so this commit is more to check how all of this works. :)
=> replace "1" with Carbon::MONDAY in console.php

resources/views/components/load-more-button.blade.php
The spinner looks like this (I put 3G throttling to show it)
https://github.com/user-attachments/assets/8e8733dd-ee15-4c8d-bab6-83e541e980c1
Also decreased intersect margin to 200 from 600 as it was not working if someone scrolls to footer too fast.
=> Feat: adding spinner in load more

app/Console/Commands/PerformDatabaseBackupCommand.php, app/Http/Controllers/QuestionController.php, app/Livewire/Concerns/ConfirmsPasswords.php, app/Models/Question.php, app/Models/User.php, app/Services/GitHub.php, app/Services/ParsableContent.php, phpstan.neon
=> Feat: adding bleeding edge in PHPStan

app/Providers/AppServiceProvider.php
Update the app service provider to use $this->app instead of the app() for checking the production environment
=> chore: consistency in app service provider

resources/views/livewire/questions/create.blade.php
=> chore: Refactor image upload UI handling

resources/views/livewire/questions/show.blade.php
fixing: https://github.com/pinkary-project/pinkary.com/issues/502
=> chore: fix width of dropdown in share button of question.

resources/views/components/back-to-top.blade.php, resources/views/components/dropdown.blade.php, resources/views/components/home-menu.blade.php, resources/views/home/feed.blade.php, resources/views/home/questions-for-you.blade.php, resources/views/home/trending-questions.blade.php, resources/views/home/users.blade.php, resources/views/layouts/app.blade.php, resources/views/layouts/navigation.blade.php, resources/views/livewire/bookmarks/index.blade.php, resources/views/livewire/feed.blade.php, resources/views/livewire/home/questions-for-you.blade.php, resources/views/livewire/home/trending-questions.blade.php, resources/views/livewire/home/users.blade.php, resources/views/livewire/questions/create.blade.php, resources/views/livewire/questions/index.blade.php, resources/views/livewire/questions/placeholder.blade.php, resources/views/livewire/questions/show.blade.php, resources/views/notifications/index.blade.php, resources/views/questions/show.blade.php
I'm working on adding some mobile updates so that way the posts span to the full width of browser on mobile (more like X).
I've also added the main navigation to the bottom of the screen. 
Here's a preview of how this looks so far
https://www.loom.com/share/12c8d1b23a214092aa2f8f1be1a10c18
I have a few more updates and checks that I will do, but wanted to see if anyone likes this direction. @nunomaduro Let me know what you think and if you think this will be good to pursue 😉
Thanks.
=> Adding mobile improvements

app/Livewire/Home/Feed.php
Reverts pinkary-project/pinkary.com#518
=> Revert "chore: refresh livewire without stubbed method"

app/Livewire/Bookmarks/Index.php, app/Livewire/Links/Index.php, app/Livewire/Navigation/NotificationsCount/Show.php, app/Livewire/Questions/Create.php, app/Livewire/Questions/Index.php, app/Livewire/Questions/Show.php
Reverts pinkary-project/pinkary.com#550
similar to: #518
=> Revert "chore: followup - refresh livewire without stubbed method"

app/Livewire/Questions/Show.php, resources/js/abbreviate.js, resources/js/app.js, resources/js/bookmark-button.js, resources/js/like-button.js, resources/views/livewire/questions/show.blade.php
The video has a glitch in the bookmark button for the icon but it is fixed.
https://github.com/user-attachments/assets/a57a12d7-fc4b-433e-9105-4913527fbcf3
=> Feat: improve bookmarks and likes

resources/views/about.blade.php
=> fix: about page

resources/views/vendor/mail/html/header.blade.php, resources/views/vendor/mail/html/themes/default.css
Vendor published header to add logo and changed css styles to match colours of site
=> Change style of default email to improve styles of emails

resources/js/bookmark-button.js, resources/js/like-button.js, resources/js/particles-effect.js
- Adds hearts in place of circles in the like button effect
- Removes effect from unlike button
- Add effect to bookmark button
https://github.com/user-attachments/assets/1ad8da7f-e2f5-45f3-ad86-d0c1afa8881a
=> Feat: improove animation like bookmark button

resources/views/livewire/questions/show.blade.php
=> Refactor: parent question display in show.blade.php

app/Livewire/Navigation/NotificationsCount/Show.php, app/Livewire/Notifications/Index.php, app/Observers/QuestionObserver.php, app/Providers/AppServiceProvider.php, resources/views/livewire/notifications/index.blade.php, resources/views/notifications/index.blade.php, tests/Unit/Livewire/Notifications/IndexTest.php
https://github.com/user-attachments/assets/bad9425f-f195-420d-867b-f723dc2fb951
=> Feat: ignore all notifications

resources/js/light-box.js
https://github.com/user-attachments/assets/fc0cbd4e-3608-4198-98a0-b6ca8a0e164c
=> Refactor light-box.js to add touch event support

resources/views/components/home-menu.blade.php, tests/Http/Home/ForYouTest.php
enhancement: rename **for you** to **following** #453
=> enhancement: rename for you to following #453

app/Livewire/Questions/Create.php, app/Models/Question.php, database/migrations/2024_09_09_150454_add_root_id_to_questions_table.php, tests/Unit/Livewire/Questions/CreateTest.php, tests/Unit/Models/QuestionTest.php
=> Feat: root id into questions

resources/views/livewire/followers/index.blade.php, resources/views/livewire/following/index.blade.php, resources/views/livewire/notifications/index.blade.php
replace `->count()` with `->isNotEmpty()` or `->isEmpty()`
=> replace "->count()" with "->is(not)empty()"

app/Livewire/Home/Feed.php, app/Livewire/Questions/Show.php, app/Models/Question.php, app/Queries/Feeds/RecentQuestionsFeed.php, resources/views/components/post-divider.blade.php, resources/views/livewire/feed.blade.php, resources/views/livewire/questions/show.blade.php, tests/Unit/Feeds/RecentQuestionsTest.php, tests/Unit/Livewire/Home/FeedTest.php, tests/Unit/Livewire/Questions/CreateTest.php, tests/Unit/Livewire/Questions/ShowTest.php, tests/Unit/Models/QuestionTest.php
After merging this we will see unique roots even unique comments or sub-comments like those shown in the video.
https://github.com/user-attachments/assets/6c5c17c5-5fb2-42b6-a2c3-2bcf56150b45
=> Feat: unique roots in feed

resources/views/livewire/link-settings/edit.blade.php
This PR removes this not used CSS classes.
=> fix: remove not needed classes.

app/Http/Controllers/QrCodeController.php, resources/views/components/modal-qr-code.blade.php, tests/Http/QrCodeTest.php
https://github.com/user-attachments/assets/7830c202-9863-4e42-8166-2e8d393790a4
=> Feat: light theme support for QR code

app/Models/User.php, app/Observers/QuestionObserver.php, tests/Unit/Models/UserTest.php, tests/Unit/Observers/QuestionObserverTest.php
It deletes notifications and questions before deleting users.
=> Feat: improve user purge

resources/views/livewire/followers/index.blade.php, resources/views/livewire/following/index.blade.php
Fix item's background color for light-mode.
=> fix: light-mode in following and followers popup at user's profile

resources/js/theme-switch.js, resources/views/layouts/app.blade.php, resources/views/layouts/components/head.blade.php
https://github.com/user-attachments/assets/92a973ad-a59c-4d77-97c7-9a62197062b7
=> Refactor: theme switch logic and update theme initialization

resources/views/components/modal-qr-code.blade.php, resources/views/layouts/components/head.blade.php
Fix QR's background color when using system mode.
=> fix: qr-code background's color in system-mode

resources/views/components/links/list-item.blade.php
=> added ref=pinkary to all the outbound links from the profile page.

app/Queries/Feeds/QuestionsFollowingFeed.php, app/Queries/Feeds/RecentQuestionsFeed.php, app/Queries/Feeds/TrendingQuestionsFeed.php, resources/views/components/thread.blade.php, resources/views/livewire/feed.blade.php, resources/views/livewire/home/questions-following.blade.php
Trending feed will get a 35-50% boost (as per my local tests).
Other feeds will get a minor boost and tread was getting them to the child instead of the root that was fixed too.
=> Feat: optimize feeds

resources/views/vendor/livewire/simple-tailwind.blade.php, resources/views/vendor/livewire/tailwind.blade.php
Missed light mode for pagination.
| Previously | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/798a8d97-a5b3-46e4-b5b0-7e28804776c3) | ![image](https://github.com/user-attachments/assets/f3e32b13-1060-41b2-b651-2a85481e41ae) |
=> chore: pagination's in light mode

resources/js/bookmark-button.js
Adds animation to "unbookmarked" state (when its count === zero) and tweaks animation to translate on X and Y.
https://github.com/user-attachments/assets/55b5180c-1def-4789-a15b-98ca5d5b7440
=> Tweaks on bookmark button animation

resources/views/livewire/links/index.blade.php
Fixes the missing ' (semicolons) on this #678 🤦
=> fix: typo on "Follow me/{name}"

app/Models/User.php, app/Services/ParsableBio.php, resources/views/livewire/links/index.blade.php, tests/Unit/Models/UserTest.php, tests/Unit/Services/BioTest.php
=> feat: usernames and links in bio

app/Queries/Feeds/QuestionsFollowingFeed.php
This pull request includes changes to the `QuestionsFollowingFeed` class to improve the query logic for fetching questions followed by a user. The most important changes involve updating the query to use `orWhereExists` for better performance.
=> feat: following-feed-speed

app/Filament/Widgets/Analytics.php, app/Providers/Filament/CitadelPanelProvider.php, tests/Http/Citadel/DashboardTest.php, tests/Unit/Citadel/Widgets/AnalyticsTest.php
=> [wip] Feat: pan-in-admin

resources/views/components/footer.blade.php, resources/views/profile/partials/verified-form.blade.php, resources/views/verified.blade.php, routes/web.php, tests/Http/Verified/IndexTest.php
Hi there! 👋
This is my first ever pull request, and I’m really excited to contribute to Pinkary! I’d love to get feedback on my changes, so I can improve and learn from the process. Please let me know if there’s anything I can adjust or any suggestions you have. Looking forward to hearing your thoughts!
Thanks for the opportunity to contribute! 😊
=> Feature: page that explains what's verified and how to get verified

app/Filament/Widgets/Analytics.php, app/Models/PanAnalytic.php, database/factories/PanAnalyticFactory.php, database/migrations/2024_10_13_234344_create_pan_tables.php, tests/Arch/ModelsTest.php, tests/Unit/Citadel/Widgets/AnalyticsTest.php
=> Feat: pan in admin

app/Livewire/Questions/Index.php, database/migrations/2024_10_13_234344_create_pan_tables.php
It's similar to https://github.com/pinkary-project/pinkary.com/pull/700
=> Chore: questions query improvement

resources/views/verified.blade.php
This PR improves the consistent design of the verified page for both light and dark modes. Additionally, it refactors the Alpine.js code to enhance clarity and maintainability.
=> Improve consistent design on verified page for light and dark mode, and refactor Alpine.js code for better clarity

package.json
2 vulnerabilities (1 moderate, 1 high)
=> Update vite dependency to version 5.4.6

app/Services/MetaData.php, resources/js/theme-switch.js, resources/views/components/link-preview-card.blade.php, resources/views/layouts/components/head.blade.php
Removes the oEmbed tweet previews.
Note: tests to be fixed.
=> Fix: remove tweet oEmbed previews

app/Models/Question.php
Changed the cast type of the pinned attribute in the Question model from bool to boolean to ensure consistency with the other cast types in the same model.
=> fix(casts): change 'pinned' cast type from bool to boolean

app/Livewire/Concerns/NeedsVerifiedEmail.php, app/Livewire/Questions/Create.php, app/Livewire/Questions/Edit.php, app/Livewire/Questions/Show.php, tests/Unit/Livewire/Concerns/NeedsVerifiedEmailTest.php
https://github.com/user-attachments/assets/b22e9887-852a-4577-b1af-122f16b3cad9
=> Feat: actions for Email verified users

composer.json, composer.lock
This pull request updates several dependencies in the `composer.json` file to ensure compatibility with newer versions and to take advantage of the latest features and fixes. The most notable changes include updates to Laravel packages and other third-party libraries.
* Updated `laravel/fortify` from `^1.21.1` to `^1.27.0` and `laravel/framework` from `^11.45.1` to `^12.21.0` to align with the latest Laravel releases.
* Updated `ryangjchandler/laravel-cloudflare-turnstile` from `^1.1` to `^2.0.3` to use the latest version of the Cloudflare Turnstile integration.
* Updated `bacon/bacon-qr-code` from `^2.0.8` to `^3.0.1` to include improvements and fixes in the QR code library.
=> Feat: Laravel 12

app/Livewire/Likes/Index.php, app/Models/Question.php, app/Policies/QuestionPolicy.php, resources/views/livewire/likes/index.blade.php, resources/views/livewire/questions/show.blade.php, tests/Unit/Livewire/Likes/IndexTest.php, tests/Unit/Livewire/Questions/ShowTest.php, tests/Unit/Models/QuestionTest.php, tests/Unit/Policies/QuestionPolicyTest.php
Right now only post owner can view who liked their posts
=> Feat: who liked my posts
