- resources/views/home/users.blade.php
- tailwind.config.js
I found this bug UI on Firefox, I have checked on chrome its fine
the problem is on max-w-md it too small for handle 4 icon menu, if I change into max-w-lg I think the width too wide, so I create custom  wide with size 30rem, and this the result
and for users or search menu I just the same as the other menus
> fix: search icon cut off in home menu components

- resources/views/components/load-more-button.blade.php
It seems 50% works well on mobile and desktop and does not have fast scrolling or footer issues either.
> chore: intersect margin value to 50%

- resources/views/livewire/questions/create.blade.php
Consolidate and organize HTML structure for the image upload components. This refactor simplifies the layout by utilizing flex containers and removes redundant elements. It also ensures better alignment and error handling within the image upload section.
This commit also prevents the camera icon overlays the text.
> Refactor image upload section in question creation

- tests/Arch/FactoriesTest.php
This PR refactors the architectural tests to remove the redundant double `ignoring` call. The change simplifies the test chain, ensuring consistency and avoiding deprecated warnings in future versions of Pest.
- Removed the second `ignoring` method call from the test chain.
- Verified that the test runs correctly without triggering deprecation warnings.
> Fix: Remove double ignore call in arch tests

- app/Livewire/Home/Feed.php
Hey @nunomaduro,
first of all what a nice code base, congrats on that :+1: 
maybe this code style is intended or you may not know about this style to trigger a `$refresh` with an `listener`
as you can see in the livewire core there is a fallback to the magic `$refresh` if there is no name
Let me know if you like this or not.
Cheers Adrian
> chore: refresh livewire without stubbed method

- resources/views/livewire/questions/create.blade.php
This is very much a baby PR, but I often thought the upload image icon was misleading. A camera tends to imply that you'll be launching the camera app, as opposed to a file upload prompt.
Twitter, for example, has an image icon to upload media, as opposed to a camera. This change aims to make a tiny but helpful improvement and address potentially incorrect user expectations.
Let me know if you have any questions regarding the motivation behind this tweak.
> fix: Update upload icon from camera to image icon for clarity

- app/EventActions/UpdateQuestionHashtags.php
- app/Http/Controllers/HashtagController.php
- app/Livewire/Home/Feed.php
- app/Queries/Feeds/RecentQuestionsFeed.php
- app/Services/ParsableContentProviders/HashtagProviderParsable.php
- resources/views/hashtag/show.blade.php
- routes/web.php
- tests/Http/Hashtag/ShowTest.php
- tests/Http/Home/FeedTest.php
- tests/Unit/Feeds/RecentQuestionsTest.php
- tests/Unit/Services/ContentProvidersTest.php
https://github.com/user-attachments/assets/1d9a0eec-4fc5-4a77-aa54-27fa85e28f0d
A pretty simple PR: make hashtags in posts a clickable link; clicking the link will take you to a feed of "recent posts with #___". This feed will show posts containing **any version (case-insensitive) of the hashtag string**, as shown in the video above (clicking `#LetsGo` also showed a post containing `#letsgo`).
Achieving this required an update to our hashtag parsing and relations updater, so the changed-files count is larger than the actual complexity of the feature.
Probably makes sense to deploy PR #564 and run that command before (or at the same time as) deploying this PR.
Up next will be the autocompletion stuff and then I think hashtags will be all done!
> Feat(hashtags): Make hashtags in posts a link to hashtag-feed

- app/Console/Commands/SyncMissingQuestionHashtags.php
- tests/Console/SyncMissingQuestionHashtagsTest.php
Adds a (intended-to-be-temporary) console command to handle historic questions with hashtags.
`php artisan app:sync-missing-hashtags {runtime=28}`
It simply loops through existing questions that do not have any related hashtags and creates+attaches hashtags as necessary.
I'm not sure how long this will take to execute, so I made the command stop after a configurable runtime. It is safe to run multiple times back to back if needed.
This shouldn't be needed after fully syncing historic questions, so the command and test can be reverted upon completion.
> feat(hashtags): add SyncMissingQuestionHashtags command

- app/Rules/Username.php
- tests/Arch/LivewireTest.php
- tests/Arch/NotificationsTest.php
- tests/Unit/Feeds/TrendingQuestionsTest.php
- tests/Unit/Livewire/Home/TrendingTest.php
- tests/Unit/Rules/UsernameTest.php
- failing rector in the `Username` rule.
- failing test in `UsernameTest`
- failing arch in `LivewireTest` and `NotificationTest`
- randomly failing `TrendingTest` (run 10 times as it passes all the time, previously it was failing one from three)
> Fix: test suites

- app/Services/Autocomplete.php
- app/Services/Autocomplete/Types/Hashtags.php
- resources/views/components/autocomplete/hashtag-item.blade.php
- tests/Unit/Services/Autocomplete/AutocompleteServiceTest.php
- tests/Unit/Services/Autocomplete/Types/HashtagsTest.php
^^^ that pic is just to show that suggestions will have capital letters when relevant. Aka, I'm not forcing a "tolower()" on the strings or anything.
Provides simple autocompletion for hashtags.
1. Will lookup hashtags in a case INsensitive manner. Ie, typing `#fo` would look for hashtags starting with `fo`, `Fo`, `FO`, etc. We have db indexes in place to handle all this efficiently.
2. The autocompletion suggestions will only show non-duplicated hashtags regarding case. So, if `foo` and `Foo` are present in the database, and `foo` has been used 10 times while `Foo` has been used 2 times, only `foo` will appear in the autocomplete suggestions.
3. Suggestions appear in descending order of most used.
4. Suggestions are limited to 8 results. Just a sensible number and keeps a scrollbar from …
> Feat(hashtags): Add hashtag autocompletion

- database/factories/HashtagFactory.php
- tests/Unit/Factories/HashtagFactoryTest.php
This pull request fixes an issue with the `HashtagFactory` where non-unique names were being generated, leading to SQL integrity constraint violations due to the unique constraint on the `name` column.
- Updated the `HashtagFactory` to use Faker's `unique()` method for generating hashtag names.
- Ensured that all generated names are unique to prevent database errors during testing or seeding.
This change resolves the `UniqueConstraintViolationException` error when creating multiple hashtags and ensures smooth database operations when using the factory.
> Fix HashtagFactory to Prevent Duplicate Name Constraint Violations

- resources/views/auth/login.blade.php
When logging in, pressing the "Enter" key triggers the password visibility toggle instead of submitting the form as expected. This creates a confusing user experience, as the password visibility is unintentionally toggled when the user tries to log in.
https://github.com/user-attachments/assets/f255588e-8b34-4c47-8e06-6255b7c1e3bc
Updated the password visibility toggle button to include `type="button"`, ensuring that pressing "Enter" submits the form as intended, while the password visibility toggle is now only activated by clicking the button.
https://github.com/user-attachments/assets/e431ddd8-3c2f-4bfa-934a-470878673adb
> Adds type button to avoid password toggle on Login Page

- resources/views/home/users.blade.php
Closes #593 
All of the "home" views use `rounded-lg` except `home.users` which accidentally had `rounded-2xl`, which caused the left/right buttons to get clipped.
Before
After
> Fix 593: Border radius mismatch for home.users container

- app/Livewire/Questions/Create.php
Fixes broken GIFs and animated WEBPs, and optimizes multi-framed images by detecting whether they have multiple frames or just a static image. It then optimizes the frames or the static image accordingly for formats like JPG, PNG, etc.
Before:
After:
https://github.com/user-attachments/assets/3a92c21f-e422-414c-8d7a-5aa4f2dfcb48
> Fix: Broken multi framed visuals on optimization 

- resources/js/theme-switch.js
1. When local storage value of 'theme' is empty string
2. Refresh, and the toggle will empty
1. Set local storage value to empty string
3. Refresh, now it'll default to 'dark'
> fix: missing theme-switch's icon when value of theme is empty string, should set to default theme

- resources/views/layouts/navigation.blade.php
- Revert the alignment (justify) to follows the previous styles
- Use backdrop-blur only, not using background so it align between dark/light mode seamlessly
> fix: revert navs, use only backdrop-blur instead of light/dark bg

- resources/views/components/links/list-item.blade.php
This is my first contribution. I recently joined Pinkary and believe that there should be a social button to redirect on anywhere click for the sharing link user (guest user on profile). Even though this only one class change, I believe it should, which is why I created this PR.
We can make a condition using $isUserProfileOwner if it feels disturbing for auth profile user.
> Updated Social button redirect on profile

- app/Models/Question.php
- app/Queries/Feeds/RecentQuestionsFeed.php
- tests/Unit/Models/QuestionTest.php
If a user posts a question and someone comments on it. after that, if the user deletes the account it starts getting 404.
> Fix: 404 after deleting user

- app/Livewire/Home/TrendingQuestions.php
Matching other feeds (Also it will add a little performance boost by skipping count query which is a bit costly here).
> Refactor TrendingQuestions to use simplePaginate instead of paginate

- resources/views/layouts/navigation.blade.php
Add a little space between each link in the Dropdown to make it look better.
Before:
After:
> Add space between dropdown links

- resources/js/theme-switch.js
- resources/views/layouts/navigation.blade.php
Its a minor fix to show light option in dark and vice versa.
as of now it shows the same label as the selected theme.
> Theme switch label

- app/Queries/Feeds/QuestionsFollowingFeed.php
- resources/views/components/thread.blade.php
- resources/views/livewire/home/questions-following.blade.php
- tests/Unit/Feeds/QuestionsFollowingTest.php
- tests/Unit/Livewire/Home/FeedTest.php
- tests/Unit/Livewire/Home/FollowingTest.php
The feed will primarily display posts and comments from users that the current user is following, or from the current user themselves. Here's a breakdown of how posts and comments are shown:
1. Posts by Following Users (or Self):
- If the root post (main post) is by a user the current user is following, it will be displayed in the feed.
2. Comments on Posts:
- If a post (root) is not by a following user, but the parent (comment) is by a following user, only the comment and parent will be shown, not the original post.
- If the root post is by a following user and the comment (parent) is not, only the root post and the comment will be displayed.
- If both the root post and the parent comment are by users the current user is not following, neither will be shown. …
> Feat: threads in following

- app/Livewire/Concerns/Followable.php
- app/Livewire/Followers/Index.php
- app/Livewire/Following/Index.php
- app/Livewire/Home/Users.php
- app/Livewire/Links/Index.php
- resources/js/app.js
- resources/js/follow-button.js
- resources/views/components/follow-button.blade.php
- resources/views/livewire/followers/index.blade.php
- resources/views/livewire/following/index.blade.php
- resources/views/livewire/home/users.blade.php
- tests/Unit/Livewire/Concerns/FollowableTest.php
- tests/Unit/Livewire/Followers/IndexTest.php
- tests/Unit/Livewire/Following/IndexTest.php
- tests/Unit/Livewire/Home/UsersTest.php
It adds follow/unfollow buttons to the following and followers lists.
White mode:
> Feat: easy follow

- resources/views/layouts/components/head.blade.php
Currently, the title shows the full answer in title.
The same title goes by default when a user bookmarks any of the post in their browser.
For a readable title, limiting the title to just 50 characters.
This will respect the SEO limits of the titles for 70 characters as well leaving room for username and "Pinkary" branding
> Limit the answers length to 50 characters in page title

- resources/views/livewire/questions/show.blade.php
> enhanced the delete confirmation of the question.

- resources/views/brand/resources.blade.php
- resources/views/privacy.blade.php
- resources/views/support.blade.php
- resources/views/terms.blade.php
Salam!
In pages, Terms, Privacy, Support and Brand, the back button was neither clickable nor redirecting to correct pages. I have fixed the issue. Kindly review and merge.
> back button bug fix

- resources/views/livewire/links/index.blade.php
- tests/Unit/Livewire/Links/IndexTest.php
This PR fixes the "Follow me on Pinkary" when sharing another user.
> Fixes always showing "Follow me on Pinkary" when sharing another user

- resources/js/image-upload.js
- resources/views/livewire/questions/create.blade.php
We currently have an edge case, where if the user has a post that is close to the max content length & they upload an image, there is no current validation, which allows the user to exceed the content limit.
This PR will add a check to ensure that the image being inserted as markdown won't pass the content limit & the image preview will still be available for the user to click and try to re-insert the markdown once the post has been shortened.
Closes #508
https://github.com/user-attachments/assets/7e38ccc8-7549-4ebb-9d7c-ceb438db86d4
> Fix: Handle case where image markdown insert passes 1000 chars

- resources/views/layouts/navigation.blade.php
This PR fixes a minor bug. I wasn't able to click on the back button when seeing a post, so i figured it was the nav blocking the button on wider displays
Now it is fixed
Please let me know if not being able to click was the intended behavior, because if it is, i think it needs some visual cue that the nav is being spanned through the whole width of the screen
> fix: nav being in front of things on wider displays

- app/Livewire/Questions/Index.php
- resources/views/livewire/questions/index.blade.php
- resources/views/livewire/questions/show.blade.php
- resources/views/profile/show.blade.php
- tests/Unit/Livewire/Questions/IndexTest.php
It's similar to the following feed just with a minor change there we show questions/posts from the user whose profile it is.
It also separates the pinned question query from the main query.
> Feat: threads in profile

- app/Services/ParsableContentProviders/CodeProviderParsable.php
- tests/Unit/Services/ContentProvidersTest.php
Fixes #672 
This change makes a small amendment to the `parse()` function to handle a user submitting a codeblock and accidentally including whitespace after the language declaration. 
The test passes and creates a snapshot - I've not seen the snapshot stuff before in my career so I'm not sure if I was supposed to commit those files too. Happy to do so if that is necessary 👍
> Fix: handle whitespace issue in codeblocks

- tests/Unit/Livewire/Questions/CreateTest.php
Currently the `composer test:unit` script fails because coverage is not 100%. This results in all GitHub action runs failing. This PR adds a test that covers the non-tested code path
> Adds a test for the optimizeImage function with an image that includes multiple frames so that overall code coverage is 100%

- app/Queries/Feeds/QuestionsFollowingFeed.php
replacement of a `where` clause with a `havingRaw` clause for improved query performance.
> Feat: following-feed-speed

- resources/views/livewire/questions/index.blade.php
- resources/views/profile/show.blade.php
This PR fixes #696 
The menu was being hidden on the overflow-hidden of a parent div, there are some solutions, but I chose the most non-destructive one that was to just add a margin-bottom to give space to the dropdown menu.
Now it's fixed:
I also removed the shadow that was on that parent div because the shadows would be displaced after the margin addition and was adding a thin "border" to the div even before this
> fix: overflowing issue when opening the last dropdown menu

- app/Livewire/Autocomplete.php
- resources/js/autocomplete.js
- resources/views/components/textarea.blade.php
- resources/views/livewire/autocomplete.blade.php
- resources/views/livewire/questions/edit.blade.php
This PR fixes #685 
When editing a post, the mention list was not being shown:
Now it's fixed:
There are 2 ways of fixing this imo without changing too much of the code. One is making an entire component just for the editing textarea, and the other one is using the same textarea blade component that already existed for the question creation. I chose the latter, but I needed the events to be scoped to the blade component, because if it wasn't, the edit textarea would trigger the autocomplete on the creation textarea and vice versa because the it assumed that only 1 component of that type would exist at a time as it emits and listens for global Livewire events.
And i removed the styling of the edit blade component because it was not really matching the styling of the textarea blade …
> fix: mentions list not showing on the edit mode

- app/Models/Bookmark.php
- app/Models/Hashtag.php
- app/Models/Like.php
- app/Models/Link.php
- app/Models/Question.php
- app/Models/User.php
Update model relationship annotations to improve type safety and clarity by using `covariant $this` in the return types.
This will ensure phpstan to pass.
More info here: https://phpstan.org/blog/whats-up-with-template-covariant#call-site-variance
Related to: https://github.com/phpstan/phpstan/issues/11857
> Refactor model relationship annotations to use 'covariant $this'

- app/Services/ParsableContentProviders/HashtagProviderParsable.php
> fix: update regex to include <div> tags in hashtag parsing

- app/Services/MetaData.php
- tests/Unit/Services/MetaDataTest.php
Add several enhancements and small refactors to the `MetaData` service, focusing on ensuring existence & image dimension check in the handling of OG image previews. Also ensures that the oEmbed iframes are the correct size too.
Additionally, new tests have been added to cover these changes.
* Added constants for preview card dimensions to `MetaData` class (`CARD_WIDTH` and `CARD_HEIGHT`).
* Introduced `ensureCorrectSize` method to set the correct size for oEmbed iframes.
* Added `checkExistsAndSize` method to validate the existence and size of images.
* Refactored `parse` method to include image validation and handle special cases for "X (formerly Twitter)".
Now it will show a normal image preview for X/twitter only if the tweet has an image or video that is used as the og:image & that …
> Fix: Add Existence & image size check + add Twitterbot user-agent for x.com

- app/Livewire/Questions/Create.php
- tests/Unit/Livewire/Questions/CreateTest.php
Addresses the security advisory [GHSA-gqq4-5mv7-ffv2](https://github.com/pinkary-project/pinkary.com/security/advisories/GHSA-gqq4-5mv7-ffv2).
This pull request refactors the `Create` class in `app/Livewire/Questions` by changing the visibility of the `uploadImages` and `deleteImage` methods from public to private.
Corresponding updates were made to the Create component unit test to use Reflection to change the visibility and invoke these methods as this is the only reason the methods were public.
> Fix: image security

- app/Livewire/Questions/Create.php
- tests/Unit/Livewire/Questions/CreateTest.php
As per discussion in #735 visibility on method `optimizeImages` changed to private to ensure no future vulnerability issues.
> Fix: Method visibility - optimizeImages

- resources/views/profile/partials/update-profile-information-form.blade.php
When registering you are not required to fill in your "Bio" data. It then does not make sense to make it a required field when editing your profile (and in fact the field is nullable and is not required in the backend when calling the patch profile route). You may be just editing your profile to change something else like your email preferences and be forced to enter something in this field.
This PR just removes this "required" property from the blade template to make it not required on the frontend.
This description is much longer than the fix itself 🤣
> Make "Bio" field not required

- app/Services/MetaData.php
After doing some research with @MrPunyapal, on the responses that the server was receiving when requesting YouTube urls, that the user has entered, we discovered it was being bot detected.
Rather than try to bypass with spoofing the User-Agent, this PR removes the initial request to YouTube by checking for the presence of youtube urls, and automatically returning the oEmbed data to display the preview.
YouTube has a really good url verification layer when they ingest the oEmbed request, so if someone tries to use a url like `https://sub.youtube.com.other.domain/watch?v=dQw4w9WgXcQ` - YouTube will still parse it and return valid oEmbed json response. As per screenshot:
Just in case they are able to find a way around this, we will allow empty responses from the oEmbed request to fall …
> Fix: Youtube Previews

- app/Services/Changelog.php
- app/Services/Git.php
- app/Services/ParsableContentProviders/CodeProviderParsable.php
- config/sponsors.php
Pint now updates all uses of `trim()` to the multibyte versions.
This PR has just run Pint globally on the repo & committed the lint changes.
> Chore: Running update to multibyte functions when running pint.

- resources/js/bookmark-button.js
- resources/js/like-button.js
- resources/views/livewire/questions/show.blade.php
When we like or bookmark any post and get into details and click on back button it lose the state and same happens with unlike or unbookmarked.
In this PR I have solved that issue.
> Fix: like and bookmark buttons with back key

- app/Models/Bookmark.php
- app/Models/Hashtag.php
- app/Models/Like.php
- app/Models/Link.php
- app/Models/Question.php
- app/Models/User.php
Refine type hints in model docblocks for clarity and consistency by replacing 'covariant $this' with '$this'.
Referring to #718
> Update type hints in model docblocks to use $this instead of covariant $this

- routes/console.php
We faced this after updating it to Laravel 12.
> fix: correct argument format for weekly notifications
